### ISSUE TITLE
HTTPS server assumes that certs/ is present in working directory

### ISSUE THREAD

**Issue by tommystanton** [masaki/Test-Fake-HTTPD#1]
First of all, thank you for this module!  It is very useful.

Commit [b3e44c](https://github.com/masaki/Test-Fake-HTTPD/commit/b3e44cf65b33182c00a2dffaa4c441dbf328bf4a) added HTTPS support, which is great, but the caveat of needing a `certs` directory is not mentioned in the documentation.

Should the user of Test::Fake::HTTPD be expected to have a `certs` directory, or should Test::Fake::HTTPD give fake certificates to HTTP::Daemon::SSL automatically?

I would be happy to help, after we decide which would be better. :)

**Comment by masaki** [comment]
thanks, added extra domain args for HTTP::Daemon::SSL at https://github.com/masaki/Test-Fake-HTTPD/commit/45f7f452e64d552860cb5584aa11e4a887e8a925
and released 0.08
